### ISSUE TITLE
Service Starts as Paused, wont restart

### ISSUE THREAD

**Issue by Artwebb1986** [SickRage/sickrage.github.io#241]
I just came home to my rebooted and updated computer
Windows 10, version 1703
OS Build 15063.138

SickRage service is paused. Doesnt allow connection @ localhost:8081. When i try to re-start the service it tells me "Windows could not start the sickrage service on Local Computer. The service did not return an error. This could be an internal windows error or an internal service error. If the problem persists, contact admin."

I went and manually updated to the newest master with git pull. 

Honestly not sure what to try next.

**Comment by sharkykh** [comment]
Hey there,
There was an issue with this and some other Windows versions,
that was fixed earlier this week.

You can follow the instructions provided at https://github.com/SickRage/SickRage/issues/3070#issuecomment-292735744.

Good luck!

**Comment by Artwebb1986** [comment]
Shit sorry i was reading the comments about updating and all that stuff for the last 45 mins and totally missed that one. 

Worked fine :)

**Comment by sharkykh** [comment]
Happens to the best of us!

**Comment by jayatthebay** [comment]
Any chance someone could put the instruction from the above link in this thread.  The repo is down so I can't access the instructions.  Thank you.

**Comment by sharkykh** [comment]
@jayatthebay Sure,
What you have to do is:
* open the Start menu
* search "SickRage"
* click "**Edit** SickRage Service"
* go to the "Process" tab
* **deselect** the checkbox next to "Console Window"
* click "Edit service"

Then:
* open the Start menu
* search "SickRage"
* click "**Stop** SickRage Service"
* open the Start menu
* search "SickRage"
* click "**Start** SickRage Service"

This should fix the issue.
