### ISSUE TITLE
INSTALL ( NEW CLEAN )

### ISSUE THREAD

**Issue by Ombouwleusden** [SickRage/sickrage.github.io#252]
How can i install now a new clean sickrage not using there instance

**Comment by abetancort** [comment]
Probably

**Comment by Ombouwleusden** [comment]
And .... now where ;-p
You guys dont have it?

**Comment by sharkykh** [comment]
well most of us run sickrage from source code, do...

https://www.reddit.com/r/sickrage/comments/6q1nvr/how_to_get_sickrage_on_windows_during_dmca/dku0rca

**Comment by miigotu** [comment]
I have it locally, but the main repo should be back up tomorrow. 10 days are up and he hasn't supplied the requisite court order to keep us down. I will be supplying him with cease and desist tomorrow.

**Comment by abetancort** [comment]
I sure hope is that way, but I am afraid that it’s going to probably take more than a cease and desist letter to solve the dispute, that’s unless someone very high in Github, Inc’s organization decides to take sides against the legal opinion of their internal General Counsel and external legal advisors.  
These type of issues rarely end without a court order. 

I believe the only company that nowadays makes judgment decisions, only on its “high value content”, is YouTube and it’s also probably the only company that has a fully staffed legal department specialized in copyright law dedicated to the evaluation of which DMCA takedown requests hold water and which don’t. If they think the claim doesn’t have enough grounds, they are not shy of holding their stance even if threatened with litigation and will usually not only represent themselves but will include the uploader with full indemnity. They want no one, big or small, thinking that just sending DMCA takedown request over any popular content will get them to a settlement.

**Comment by miigotu** [comment]
They don't make a decision about it at all. After I sent the DMCA Counter Claim he refused to rescind the DMCA takedown. After the refusal he had 10 days to provide GitHub with proof that he obtained a court order to restrain me from using this content. He has not done so, and the 10 days has passed.

This is all normal GitHub policy on how to manage DMCA takedowns. There is nothing special about it.  My letter to him afterwards will be a ceast and desist warning that any further action to harm me or the project will be met with litigation.

If you do not have personal experience with how this works please don't try to educate me.  We did not infringe on any copyright that he owned, and the original copyright owner is on our side (Even though by license that copyright is shared among all subsequent contributors).

I have spoken to GitHub directly and THESE are the FACTS

**Comment by miigotu** [comment]
Small correction to my previous comment. They mean __business days__
![image](https://user-images.githubusercontent.com/390379/28859504-790b59ce-770c-11e7-93e8-2f961f7206ab.png)

**Comment by OmgImAlexis** [comment]
It really needs to be stated more clearly that it's 10 *business* days since they're an international company I had expected 10 actual days. 😞

**Comment by AubreyKloppers** [comment]
I started using SickRage AS the split happened and at the time did not know the difference between the two releases.  After a struggle with the "other" release I found this one and never looked back.  I also got some nagging emails from the "other" release asking to go back.  After (nicely) asking the "other" guy to stop harassing me, I got kicked of his forum...  Pity I did not keep the emails!

ps - Good for you, @miigotu for not letting this jerk walk all over this release...

**Comment by QuentinJ54** [comment]
I look forward to the repository being opened again :)
Would you be able to do a SPK for synology?
I thank your team

**Comment by miigotu** [comment]
@HLFH has been blocked now for trying to plug links to the other source here.

**Comment by miigotu** [comment]
@QuentinJ54 syno-community already has a spk for this version.

**Comment by QuentinJ54** [comment]
Could you give me the link of this one or the procedure to follow? 
Because the only one I find is that of Echelnn. The others it tells me error when the packet is distributed.
Thank you

**Comment by sirmentos** [comment]
Any thoughts on whether this will be back before monday or do we all get to suffer through the weekend?

**Comment by QuentinJ54** [comment]
The repository is open again :).
But impossible to install on synology :(

**Comment by sharkykh** [comment]
@QuentinJ54 Did you try https://github.com/SickRage/SickRage/wiki/Switching-your-Synology's-Sickrage-to-the-new-repository?

**Comment by sharkykh** [comment]
Closing this issue as the main repo is now available.
https://github.com/SickRage/SickRage
