### ISSUE TITLE
Missing time zone for network: Paramount Network.

### ISSUE THREAD

**Issue by chrillep** [SickRage/sickrage.github.io#266]
Missing time zone for network: Paramount Network. Check valid network is set in indexer (theTVDB) before filing issue.

**Comment by chrillep** [comment]
https://github.com/SickRage/sickrage.github.io/blob/master/sb_network_timezones/network_timezones.txt

**Comment by johanndt** [comment]
Also `Missing time zone for network: Stargate Command. Check valid network is set in indexer (theTVDB) before filing issue.`
